# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: Research
    url: projects/
    weight: 11
  - name: Publications
    url: publication/
    weight: 12
  - name: People
    url: people/
    weight: 13
  - name: Join Us!
    url: contact/
    weight: 20